"""empty message

Revision ID: df1bb5efe241
Revises: 
Create Date: 2022-09-15 11:17:08.240058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1bb5efe241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('moisture', sa.REAL(), nullable=True),
    sa.Column('temperature', sa.REAL(), nullable=True),
    sa.Column('light', sa.REAL(), nullable=True),
    sa.Column('waterLevel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_history_light'), 'history', ['light'], unique=False)
    op.create_index(op.f('ix_history_moisture'), 'history', ['moisture'], unique=False)
    op.create_index(op.f('ix_history_temperature'), 'history', ['temperature'], unique=False)
    op.create_index(op.f('ix_history_waterLevel'), 'history', ['waterLevel'], unique=False)
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moisMin', sa.Integer(), nullable=True),
    sa.Column('moisMax', sa.Integer(), nullable=True),
    sa.Column('tempMin', sa.Integer(), nullable=True),
    sa.Column('tempMax', sa.Integer(), nullable=True),
    sa.Column('lightMax', sa.Integer(), nullable=True),
    sa.Column('lightMin', sa.Integer(), nullable=True),
    sa.Column('wateringTime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_lightMax'), 'setting', ['lightMax'], unique=False)
    op.create_index(op.f('ix_setting_lightMin'), 'setting', ['lightMin'], unique=False)
    op.create_index(op.f('ix_setting_moisMax'), 'setting', ['moisMax'], unique=False)
    op.create_index(op.f('ix_setting_moisMin'), 'setting', ['moisMin'], unique=False)
    op.create_index(op.f('ix_setting_tempMax'), 'setting', ['tempMax'], unique=False)
    op.create_index(op.f('ix_setting_tempMin'), 'setting', ['tempMin'], unique=False)
    op.create_index(op.f('ix_setting_wateringTime'), 'setting', ['wateringTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_wateringTime'), table_name='setting')
    op.drop_index(op.f('ix_setting_tempMin'), table_name='setting')
    op.drop_index(op.f('ix_setting_tempMax'), table_name='setting')
    op.drop_index(op.f('ix_setting_moisMin'), table_name='setting')
    op.drop_index(op.f('ix_setting_moisMax'), table_name='setting')
    op.drop_index(op.f('ix_setting_lightMin'), table_name='setting')
    op.drop_index(op.f('ix_setting_lightMax'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_history_waterLevel'), table_name='history')
    op.drop_index(op.f('ix_history_temperature'), table_name='history')
    op.drop_index(op.f('ix_history_moisture'), table_name='history')
    op.drop_index(op.f('ix_history_light'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
